name: bus_tracker_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  dio: ^5.4.3+1
  google_fonts: ^6.2.1

  # Firebase Packages
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

  # Map & Location Packages
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  permission_handler: ^11.3.1
  flutter_polyline_points: ^2.0.0

  # Helper Packages
  uuid: ^4.4.0
  logging: ^1.2.0
  shared_preferences: ^2.2.3 # Updated to a more recent version
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_local_notifications: ^17.2.1
  provider: ^6.0.0
  flutter_volume_controller: ^1.1.0
  vibration: ^3.1.3

  # --- ADDED FOR CONTINUOUS BACKGROUND TRACKING ---
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    # If you have specific files, you can list them like this:
    # - assets/title.png
    # - assets/mysore.png
    # - assets/google_logo.png
    # - assets/bus_icon.png
    # - assets/bus_stop.png

